[[cameras]]
name = 'Camera 1'
id = 'cam1'
hostname = '10.22.240.52'
path = '/cam/realmonitor?channel=1&subtype=0&proto=Onvif'
port = 80
user = 'admin'
password = 'L2F4440B'

[[cameras]]
name = 'Camera 3'
id = 'cam3'
hostname = '10.22.240.54'
path = '/cam/realmonitor?channel=1&subtype=0&proto=Onvif'
port = 80
user = 'admin'
password = 'L2C6160F'

[[cameras]]
name = 'Camera 4'
id = 'cam4'
hostname = '10.22.240.55'
path = '/cam/realmonitor?channel=1&subtype=0&proto=Onvif'
port = 80
user = 'admin'
password = 'L22F0A5E'

[[cameras]]
name = 'Camera 5'
id = 'cam5'
hostname = '10.22.240.56'
path = '/cam/realmonitor?channel=1&subtype=0&proto=Onvif'
port = 80
user = 'admin'
password = 'L2321800'

